package:
  name: dicom2fem
  version: "1.0.38"

source:
  git_rev: 1.0.38
  git_url: .
#  fn: imtools-0.0.17.tar.gz
#  url: https://pypi.python.org/packages/source/i/imtools/imtools-0.0.17.tar.gz
#  md5: 2c88dfda63b4b8dc2f849e4e0218f7fb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - imtools = imtools:main
    #
    # Would create an entry point called imtools that calls imtools.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pyyaml
    - matplotlib
    - mock
    - nose
    - imcut
    - vtk
    - pyqt 4.11.*

  run:
    - python
    - numpy
    - scipy >=0.18.1
    - pyyaml
    - matplotlib
    - imcut
    - vtk
    - pyqt 4.11.* # -c menpo

test:
  # Python imports
  imports:
    - dicom2fem

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/vlukes/dicom2fem
  license: BSD License
  summary: 'Generation of finite element meshes using computed tomography scans'

# See
# http://docs.continuum.io/conda/build.html for
# more information aboua meta.yaml
