# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mailmojo
from mailmojo.models.newsletter_segments import NewsletterSegments  # noqa: E501
from mailmojo.rest import ApiException


class TestNewsletterSegments(unittest.TestCase):
    """NewsletterSegments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewsletterSegments(self):
        """Test NewsletterSegments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mailmojo.models.newsletter_segments.NewsletterSegments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
