ACCOUNT_MANAGER = "ACCOUNT_MANAGER"
ADMINISTRATION = "ADMINISTRATION"
AUDITOR = "AUDITOR"
CLINIC = "CLINIC"
DATA_MANAGER = "DATA_MANAGER"
DATA_QUERY = "DATA_QUERY"
EVERYONE = "EVERYONE"
EXPORT = "EXPORT"
LAB = "LAB"
LAB_VIEW = "LAB_VIEW"
PHARMACY = "PHARMACY"
PII = "PII"
PII_VIEW = "PII_VIEW"
REVIEW = "REVIEW"

DEFAULT_GROUP_NAMES = [
    ACCOUNT_MANAGER,
    ADMINISTRATION,
    AUDITOR,
    CLINIC,
    DATA_MANAGER,
    DATA_QUERY,
    EVERYONE,
    EXPORT,
    LAB,
    LAB_VIEW,
    PHARMACY,
    PII,
    PII_VIEW,
    REVIEW,
]
