[tool.poetry]
name = "herb"
version = "0.1.0"
description = "Effortless Offline Backups"
authors = ["eukaryote <eukaryote31@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
more_itertools = "^7.1"
sqlalchemy = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
