# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(help_text='np. 96-316', max_length=255, verbose_name='Kod pocztowy')),
                ('city', models.CharField(help_text='np. Warszawa', max_length=255, verbose_name='Miasto')),
                ('street', models.CharField(blank=True, help_text='np. Wiejska', max_length=255, null=True, verbose_name='Ulica')),
                ('country', models.CharField(default=b'PL', max_length=2, verbose_name='Kraj')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('zip_code', 'city', 'street')]),
        ),
    ]
