# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from model_server.apis import predict_pb2 as model__server_dot_apis_dot_predict__pb2
from model_server.protos import model_info_pb2 as model__server_dot_protos_dot_model__info__pb2


class ModelServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPredictions = channel.unary_unary(
        '/ModelServer.ModelServer/GetPredictions',
        request_serializer=model__server_dot_apis_dot_predict__pb2.PredictRequest.SerializeToString,
        response_deserializer=model__server_dot_apis_dot_predict__pb2.PredictResponse.FromString,
        )
    self.GetModelInfo = channel.unary_unary(
        '/ModelServer.ModelServer/GetModelInfo',
        request_serializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.SerializeToString,
        response_deserializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.FromString,
        )


class ModelServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPredictions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPredictions': grpc.unary_unary_rpc_method_handler(
          servicer.GetPredictions,
          request_deserializer=model__server_dot_apis_dot_predict__pb2.PredictRequest.FromString,
          response_serializer=model__server_dot_apis_dot_predict__pb2.PredictResponse.SerializeToString,
      ),
      'GetModelInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelInfo,
          request_deserializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.FromString,
          response_serializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ModelServer.ModelServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
