sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"            # Python 3.7
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "nightly"
    - python: "pypy"
    - python: "pypy3"
install: pip install -U pytest pytest-runner
script: python setup.py pytest

