
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-08T22:39:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "327c5b57bc7c2743b6e93dfc7f3e7a8a10287b93",
 "version": "0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
