# Generated by Django 2.1.7 on 2019-04-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0017_instanceoperation_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceoperation',
            name='auto',
        ),
        migrations.AddField(
            model_name='instanceoperation',
            name='manual',
            field=models.BooleanField(default=True),
        ),
    ]
