# Generated by Django 2.2 on 2019-04-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0033_auto_20190420_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupoperation',
            options={'ordering': ['-started_time', '-pk'], 'verbose_name': 'group operation'},
        ),
    ]
