# Generated by Django 2.2 on 2019-04-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0034_auto_20190420_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupoperation',
            options={'ordering': ['-started_time', '-completed_time', '-pk'], 'verbose_name': 'group operation'},
        ),
        migrations.AlterModelOptions(
            name='instanceoperation',
            options={'ordering': ['-started_time', '-completed_time', '-pk'], 'verbose_name': 'operation'},
        ),
    ]
