[tool.poetry]
name = "diff-1c"
version = "6.4.0"
description = "Diff utility for 1C:Enterprise"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cujoko/diff-1c"
keywords = ["1c", "diff", "v8reader", "v8unpack", "gcomp"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
diff1c = "diff_1c.__main__:run"

[tool.poetry.dependencies]
python = "^3.7"
cjk-commons = "^3.3"
parse-1c-build = "^5.5"
loguru = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
