
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-08T20:21:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "aeccf069bdbc7c7c3a32a552bc9d32898a557a6b",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
