
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: examples/src/python/kengste/hello/main

from setuptools import setup

setup(**{
    'description': 'Trying for fun',
    'package_data': {
    },
    'package_dir': {
        '': 'src',
    },
    'install_requires': [
    ],
    'version': '0.0.4',
    'zip_safe': True,
    'packages': [
        'kengste',
        'kengste.hello',
        'kengste.hello.main',
    ],
    'classifiers': [
        'Intended Audience :: Developers',
        'Programming Language :: Python',
    ],
    'name': 'kengste',
})
