# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(help_text='Name of the block, will be used in HTML as a reference. Please do not update.', max_length=256, unique=True, verbose_name='Block Name')),
            ],
        ),
        migrations.CreateModel(
            name='PageBlockTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('de', 'German'), ('el', 'Greek'), ('cs', 'Czech'), ('ca', 'Catalan'), ('es', 'Spanish'), ('sl', 'Slovene')], max_length=2)),
                ('default_translation', models.BooleanField(default=False)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=1024)),
                ('contents_md', models.TextField()),
                ('contents_html', models.TextField(editable=False)),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page_block.PageBlock')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pageblocktranslation',
            unique_together=set([('page_block', 'language')]),
        ),
    ]
