# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_block', '0003_auto_20171004_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('el', 'Greek'), ('cs', 'Czech'), ('ca', 'Catalan'), ('es', 'Spanish'), ('sl', 'Slovene'), ('it', 'Italian')], max_length=2),
        ),
    ]
