# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_block', '0005_auto_20171025_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlockUrl',
            fields=[
                ('basepageblocktranslation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page_block.BasePageBlockTranslation')),
                ('url', models.URLField()),
            ],
            bases=('page_block.basepageblocktranslation',),
        ),
    ]
