# Generated by Django 2.2.2 on 2019-07-03 19:55

from django.db import migrations, models
import znbdownload.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('private', models.BooleanField(default=False)),
                ('private_file', models.FileField(blank=True, null=True, storage=znbdownload.storage.S3PrivateStorage(), upload_to='')),
            ],
        ),
    ]
