
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-28T09:08:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3baa06cddd2b7ddc743d02abcd56217522fe8959",
 "version": "0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
