language: python
python:
- 2.7
- 3.5
- 3.6
install:
- pip install -U pip setuptools
- pip install -e .[testing]
script:
- pylint -j $(nproc) --rcfile=.pylintrc backslash tests
- py.test tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: QERgKUrFAiCgfUswgqg1kNJpAE9giHeYkvoeMRXkucQ9Eq3z3v8rZPm63o4idXrQAR5i3PbkPix2pZ4h+Jc7EbmihSECXxVuivs7LtEUY34fNIDMBlpHUkvJClS9unMIzXipLzTJxQR0ZMbggz1bTwX9NaM44ZvX+22pLHYEom8=
  on:
    tags: true
    repo: getslash/backslash-python
    python: "3.6"
