# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
