# Generated by Django 2.0.6 on 2018-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('message', models.TextField()),
                ('is_editable', models.BooleanField(default=False, verbose_name="Autoriser l'édition")),
                ('is_deletable', models.BooleanField(default=False, verbose_name='Autoriser la suppression')),
            ],
        ),
    ]
