#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyatsa']

package_data = \
{'': ['*'], 'pyatsa': ['.empty/*', '.ipynb_checkpoints/*', 'tests/*']}

install_requires = \
['requests',
 'docutils',
 'requests_download',
 'pytoml',
 'numpy',
 'shapely',
 'rasterio',
 'geojson',
 'planet',
 'scipy',
 'scikit-image']

setup(name='pyatsa',
      version='0.1',
      description='The ATSA cloud masking method for Planetscope 4-band imagery',
      author='Ryan Avery',
      author_email='ravery@ucsb.edu',
      url='https://github.com/agroimpacts/pyatsa',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>3.4',
     )
