[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "firestone"
author = "DK"
author-email = "dkainama@jouwomgeving.nl"
home-page = "https://bitbucket.org/jouwomgeving/firestone"

