#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['firestone']

package_data = \
{'': ['*']}

setup(name='firestone',
      version='0.0.1',
      description='Firestone',
      author='DK',
      author_email='dkainama@jouwomgeving.nl',
      url='https://bitbucket.org/jouwomgeving/firestone',
      packages=packages,
      package_data=package_data,
     )
