# Generated by Django 2.1.3 on 2019-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='groupfield',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='editable',
        ),
        migrations.AddField(
            model_name='field',
            name='form_editable',
            field=models.BooleanField(default=True, verbose_name='表单可编辑'),
        ),
        migrations.AddField(
            model_name='field',
            name='list_editable',
            field=models.BooleanField(default=True, verbose_name='列表可编辑'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='form_editable',
            field=models.BooleanField(default=True, verbose_name='表单可编辑'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='list_editable',
            field=models.BooleanField(default=True, verbose_name='列表可编辑'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='form_editable',
            field=models.BooleanField(default=True, verbose_name='表单可编辑'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='list_editable',
            field=models.BooleanField(default=True, verbose_name='列表可编辑'),
        ),
    ]
