# coding: utf-8

"""
    Endpoints

    Endpoints API for different services in SKIL  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skil_client
from skil_client.models.google_storage_resource_details import GoogleStorageResourceDetails  # noqa: E501
from skil_client.rest import ApiException


class TestGoogleStorageResourceDetails(unittest.TestCase):
    """GoogleStorageResourceDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoogleStorageResourceDetails(self):
        """Test GoogleStorageResourceDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skil_client.models.google_storage_resource_details.GoogleStorageResourceDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
