# coding: utf-8

"""
    Endpoints

    Endpoints API for different services in SKIL  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skil_client
from skil_client.models.json_array_response import JsonArrayResponse  # noqa: E501
from skil_client.rest import ApiException


class TestJsonArrayResponse(unittest.TestCase):
    """JsonArrayResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonArrayResponse(self):
        """Test JsonArrayResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skil_client.models.json_array_response.JsonArrayResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
