from staplesremoval.staples_detector import *
from staplesremoval.inpainting import *
from staplesremoval.remove_staples import *
from staplesremoval.trapezoid_fuzzy_color_segmentation import trapezoid_fuzzy_color_segmentation
from staplesremoval.triangle_fuzzy_color_segmentation import triangle_fuzzy_color_segmentation