---
applications:
- guillotina_authentication
databases:
  db:
    storage: DUMMY_FILE
host: localhost
port: 8080
root_user:
  password: root
auth_extractors:
- guillotina.auth.extractors.BearerAuthPolicy
- guillotina.auth.extractors.BasicAuthPolicy
- guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
- guillotina.auth.validators.SaltedHashPasswordValidator
- guillotina.auth.validators.JWTValidator
cors:
  allow_origin:
  - http://localhost:8080
  - "chrome-extension://*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - PUT
  - OPTIONS
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
jwt:
  secret: foobar
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
auth_providers:
  twitter:
    configuration:
      consumer_key: foobar
      consumer_secret: foobar
  google:
    configuration:
      client_id: foobar
      client_secret: foobar
    scope: openid email
  github:
    configuration:
      client_id: foobar
      client_secret: foobar
    scope: read:user
  hydra:
    configuration:
      client_id: auth-code-client
      client_secret: secret
      base_url: http://localhost:4444/
      authorize_url: http://localhost:4444/oauth2/auth
      access_token_url: http://localhost:4444/oauth2/token
    state: true
    scope: openid offline

# frontend url to handle storing auth
auth_callback_url: http://localhost:8080/foobar
