
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-21T21:23:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d66c20b500c0a231d0bd2c0e9b57c704391f1f3a",
 "version": "0.0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
