# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mailmojo
from mailmojo.models.newsletter_statistics import NewsletterStatistics  # noqa: E501
from mailmojo.rest import ApiException


class TestNewsletterStatistics(unittest.TestCase):
    """NewsletterStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewsletterStatistics(self):
        """Test NewsletterStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mailmojo.models.newsletter_statistics.NewsletterStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
