---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - 'status-success=cr8'
      - 'status-success=LGTM analysis: Python'
    name: default
  - name: Delete branch after merge
    actions:
      delete_head_branch: {}
    conditions:
      - merged
