---
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7-dev
  - nightly

install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
  - chmod +x ./install-jdk.sh
  - ./install-jdk.sh -f 10
  - pip install pycodestyle asyncpg coverage codecov
  - pip install .

script:
  - coverage run --source=cr8 -m unittest -v
  - pycodestyle cr8

after_success:
  - codecov

notifications:
  email: false
