# Generated by Django 2.2.2 on 2019-06-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0002_auto_20190614_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='list_editable',
            field=models.BooleanField(default=False, verbose_name='列表可编辑'),
        ),
        migrations.AlterField(
            model_name='groupfield',
            name='list_editable',
            field=models.BooleanField(default=False, verbose_name='列表可编辑'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='list_editable',
            field=models.BooleanField(default=False, verbose_name='列表可编辑'),
        ),
    ]
