# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_foo_yesorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
