# Generated by Django 2.1.5 on 2019-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0008_subdivision_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdivision',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на подробный ресурс'),
        ),
    ]
