# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-06 01:25
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards_app', '0001_initial'),
        ('cms', '0020_old_tree_cleanup'),
        ('dash_docs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashdoc',
            name='dashboard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards_app.Dashboard'),
        ),
        migrations.AddField(
            model_name='dashdoc',
            name='sidebar_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_sidebar_content', slotname='documentation_sidebar_content', to='cms.Placeholder'),
        ),
    ]
