"""
Django settings for snowland_astardownload project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qbyvln5k1j8u@ja8cj8dpg33t955ynj@7!$^2qa$lhm#lmn0s4'

# Application definition
DEBUG = False
INSTALLED_APPS = [
    'django.contrib.admin',
    # 'django.contrib.auth',
    'djangohelper.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'djangohelper.contrib.friendlink',
    # 'djangohelper.contrib.developer'
]

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = "auth.User"


LANGUAGE_SESSION_KEY = 'snowland-language'