[tool.poetry]
name = "zokrates-pycrypto"
version = "0.2.0"
description = "Accompanying crypto application code for the zkSNARKs toolbox ZoKrates"
authors = ["sdeml <stefandeml@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
bitstring = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
