# Generated by Django 2.2 on 2019-06-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190617_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataengine',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'relational'), (1, 'raw'), (2, 'freetext'), (3, 'semistructed'), (4, 'event'), (5, 'graph'), (6, 'star')]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'relational'), (1, 'raw'), (2, 'freetext'), (3, 'semistructed'), (4, 'event'), (5, 'graph'), (6, 'star')], null=True),
        ),
    ]
