dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: 0kjpm+3P8V0jJbOrxAzqRsdlIBbyVMHgXXYolnkDJUSfyoX2iCaK4iyx3IabpBDz4yUPJAXr9nG+oMryRD3vdgZ+RmtcAS2cJlN1LiKrkE5IAQWQwjzcTS7GOmVXpJEstW1qvV1q/+6lKEi2TQ3JgXmA6AoAMZwIsix43QRjoS5xWKuU+1ZSrRPgs4ZrPdbs7BZ5N8IE7/mYRa8J06ICeLh/0jUU2VKKaqSvr5npeMt4kkEJlkFB4hWpCcoLY7yBOeGZ1wQgfJ38FFpFUvcamnRZVt+A3oEjUeznjQKFkRd84Ezu2ASzyiOmi5FPCP4L1dX8P2cOHgRB15vTqDcbUnb7AQnLoWMTMlU9CF0cRdw2DCvGqmWMuOgIrbNoqngMrvG7U53oz3x18QGaTL2q/GZZ0GInnDkftK18U2xbrmGGOxTft2mPMqvEZrGEFD6FsstFrqlN0vQhuQ1HuxxljOARLdXRaMVTvSJxwIMj56dPDZOK3uy0JGA11/VpT7mmORANgbQOCfdF9bHuLKlXqqVcinZ046pK8Y4nK842Dx1glkRtmXQ3hv6CbvFYDjrDlCjreQcnTtIX+euA1ejiWMR9zS4iU7EKQfgda1+N/a857XQ6g2OqwZsc+3j/HEqZz6NuppiS27duMse4NI1xnGDt7DBkmqWgWmG1wfJTOco=
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_max31856.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-max31856 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
