[tool.poetry]
name = "aisc"
version = "0.1.8"
description = "AISC Helper Tools"
authors = ["MB <mb@aisc.io>"]
license="MIT"
readme="README.md"
homepage="https://github.com/a1sc/aisc_tools"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
