
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-27T11:22:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea141f1900ecc36ffda847931161ff4a24473b6a",
 "version": "1.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
