# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('runtime', '0002_event_processinstance_workitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0002_auto_20181218_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workitems', to='workflow.Activity'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workitems', to='runtime.ProcessInstance'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='others_workitems_from',
            field=models.ManyToManyField(related_name='_workitem_others_workitems_from_+', to='runtime.WorkItem'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='pull_roles',
            field=models.ManyToManyField(related_name='pull_workitems', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='push_roles',
            field=models.ManyToManyField(related_name='push_workitems', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='workitem_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workitems_to', to='runtime.WorkItem'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.Process'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runtime.WorkItem'),
        ),
    ]
