[tool.poetry]
name = "bputils"
version = "0.1.0"
description = "BP utils"
authors = ["yokotoka <hey@yokotoka.is>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
grpcio = "^1.22"
grpcio-tools = "^1.22"
protobuf = "^3.8"
grpclib = "^0.2.5"
python-dotenv = "^0.10.3"

[tool.poetry.dev-dependencies]
python = "^3.7"
grpcio = "^1.22"
grpcio-tools = "^1.22"
protobuf = "^3.8"
grpclib = "^0.2.5"
python-dotenv = "^0.10.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
