maxcrossing:
    - 2
min_length:
    - 20
overlap_thr:
    - 1
overlap_thr_list:
    - null
step_list:
    - 0.2
    - 0.3
    - 0.4
    - 0.5
curv_thr_list:
    - 60
    - 30
    - 10
life_run:
    - False
nilearn_parc_atlases:
    - 'atlas_harvard_oxford'
    - 'atlas_aal'
    - 'atlas_destrieux_2009'
    - 'atlas_talairach_gyrus'
    - 'atlas_talairach_ba'
    - 'atlas_talairach_lobe'
nilearn_coord_atlases:
    - 'coords_power_2011'
    - 'coords_dosenbach_2010'
nilearn_prob_atlases:
    - 'atlas_msdl'
    - 'atlas_pauli_2017'
available_models:
    func_models:
      - 'corr'
      - 'sps'
      - 'cov'
      - 'partcorr'
      - 'QuicGraphicalLasso'
      - 'QuicGraphicalLassoCV'
      - 'QuicGraphicalLassoEBIC'
      - 'AdaptiveQuicGraphicalLasso'
    struct_models:
      - 'csa'
      - 'tensor'
      - 'csd'
