# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTerminal',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='log_terminal_client_logterminal', serialize=False, to='cms.CMSPlugin')),
                ('terminal_lines', models.CharField(default=100, max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PluginPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resized', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=50, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('top', models.CharField(max_length=50, null=True)),
                ('left', models.CharField(max_length=50, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_terminal_client.LogTerminal')),
            ],
        ),
    ]
