# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Contact(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, added=None, email=None, first_name=None, last_name=None, list_associations=None, name=None, status=None, status_changed=None, tags=None):
        """
        Contact - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'added': 'datetime',
            'email': 'str',
            'first_name': 'str',
            'last_name': 'str',
            'list_associations': 'list[ContactListAssociations]',
            'name': 'str',
            'status': 'str',
            'status_changed': 'datetime',
            'tags': 'list[str]'
        }

        self.attribute_map = {
            'added': 'added',
            'email': 'email',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'list_associations': 'list_associations',
            'name': 'name',
            'status': 'status',
            'status_changed': 'status_changed',
            'tags': 'tags'
        }

        self._added = added
        self._email = email
        self._first_name = first_name
        self._last_name = last_name
        self._list_associations = list_associations
        self._name = name
        self._status = status
        self._status_changed = status_changed
        self._tags = tags

    @property
    def added(self):
        """
        Gets the added of this Contact.

        :return: The added of this Contact.
        :rtype: datetime
        """
        return self._added

    @added.setter
    def added(self, added):
        """
        Sets the added of this Contact.

        :param added: The added of this Contact.
        :type: datetime
        """

        self._added = added

    @property
    def email(self):
        """
        Gets the email of this Contact.

        :return: The email of this Contact.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this Contact.

        :param email: The email of this Contact.
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this Contact.

        :return: The first_name of this Contact.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this Contact.

        :param first_name: The first_name of this Contact.
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this Contact.

        :return: The last_name of this Contact.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this Contact.

        :param last_name: The last_name of this Contact.
        :type: str
        """

        self._last_name = last_name

    @property
    def list_associations(self):
        """
        Gets the list_associations of this Contact.

        :return: The list_associations of this Contact.
        :rtype: list[ContactListAssociations]
        """
        return self._list_associations

    @list_associations.setter
    def list_associations(self, list_associations):
        """
        Sets the list_associations of this Contact.

        :param list_associations: The list_associations of this Contact.
        :type: list[ContactListAssociations]
        """

        self._list_associations = list_associations

    @property
    def name(self):
        """
        Gets the name of this Contact.
        Full name of the contact. Will, if present, take precedence over first_name and last_name.

        :return: The name of this Contact.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Contact.
        Full name of the contact. Will, if present, take precedence over first_name and last_name.

        :param name: The name of this Contact.
        :type: str
        """

        self._name = name

    @property
    def status(self):
        """
        Gets the status of this Contact.

        :return: The status of this Contact.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this Contact.

        :param status: The status of this Contact.
        :type: str
        """
        allowed_values = ["a", "u", "b", "d"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def status_changed(self):
        """
        Gets the status_changed of this Contact.

        :return: The status_changed of this Contact.
        :rtype: datetime
        """
        return self._status_changed

    @status_changed.setter
    def status_changed(self, status_changed):
        """
        Sets the status_changed of this Contact.

        :param status_changed: The status_changed of this Contact.
        :type: datetime
        """

        self._status_changed = status_changed

    @property
    def tags(self):
        """
        Gets the tags of this Contact.

        :return: The tags of this Contact.
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this Contact.

        :param tags: The tags of this Contact.
        :type: list[str]
        """

        self._tags = tags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
