
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "778d2a7e4c5562a277045e540198421ff752bf39",
 "version": "0.22.21.b4518"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
