# configuration for https://travis-ci.org
dist: xenial
sudo: required

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - TEST_SUITE=simp_le_suite
matrix:
  fast_finish: true
  include:
  - python: "3.7"
    env: TEST_SUITE=lint_suite
  - python: "3.7"
    env: ARCH=amd64 TEST_SUITE=docker_suite FROM=alpine:3.7 IMAGE=zenhack/simp_le:$ARCH
  - python: "3.7"
    env: ARCH=arm64 TEST_SUITE=docker_suite FROM=multiarch/alpine:arm64-v3.7 IMAGE=zenhack/simp_le:$ARCH
  - python: "3.7"
    env: ARCH=arm TEST_SUITE=docker_suite FROM=multiarch/alpine:armhf-v3.7 IMAGE=zenhack/simp_le:$ARCH
  allow_failures:
  - env: ARCH=arm64 TEST_SUITE=docker_suite FROM=multiarch/alpine:arm64-v3.7 IMAGE=zenhack/simp_le:$ARCH
  - env: ARCH=arm TEST_SUITE=docker_suite FROM=multiarch/alpine:armhf-v3.7 IMAGE=zenhack/simp_le:$ARCH

addons:
  hosts:
    - le.wtf
    - le2.wtf

install:
  - ./tests/install.sh $TEST_SUITE
script:
  - ./tests/test-suite.sh $TEST_SUITE

notifications:
  irc:
    channels:
      - "irc.freenode.org#simp_le"
    use_notice: true
    skip_join: true
