# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktranslation',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
