---
- name: This is a recipe for how to cook with ogr
  hosts: all
  tasks:
  - name: Install all packages needed to hack on ogr.
    dnf:
      name:
      - python3-pip
      - python3-setuptools
      - git
      - python3-setuptools_scm
      - python3-setuptools_scm_git_archive
      - python3-wheel  # for bdist_wheel
  - name: Install latest twine for sake of check command
    pip:
      name:
      - twine  # we need newest twine, b/c of the check command
      - readme_renderer[md]
      state: latest
  - name: Install dependencies for git APIs
    dnf:
      name:
      - python3-requests
      - python3-pygithub
      - python3-gitlab
      state: present
  - name: stat /src
    stat:
      path: /src
    tags:
    - no-cache
    register: src_path
  - name: Let's make sure /src is present
    assert:
      that:
      - 'src_path.stat.isdir'
  # this requires to have sources mounted inside at /src
  - name: Install ogr from the current working directory
    pip:
      name: /src
