# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .module import Module


class AzureMLModuleVersion(Module):
    """AzureMLModuleVersion.

    :param module_id:
    :type module_id: str
    :param data:
    :type data: ~swagger.models.ModuleEntity
    :param interface:
    :type interface: ~swagger.models.EntityInterface
    """

    _attribute_map = {
        'module_id': {'key': 'ModuleId', 'type': 'str'},
        'data': {'key': 'Data', 'type': 'ModuleEntity'},
        'interface': {'key': 'Interface', 'type': 'EntityInterface'},
    }

    def __init__(self, module_id=None, data=None, interface=None):
        super(AzureMLModuleVersion, self).__init__(data, interface)
        self.module_id = module_id
