
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-28T05:48:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f276b5516cf9768c96b1a0f3d12eca42fa442cc",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
