---
dist: xenial
# Config file for automatic testing at travis-ci.org

services:
  - docker
language: python

branches:
  only:
    - master
    - /[0-9]+\.[0-9]+\.[0-9]+(.*)?$/

cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --user tox tox-pyenv; else python -m pip install tox tox-pyenv; fi
jobs:
  fast_finish: true
  include:
    - name: lint,py27,molecule
      env: TOXENV=lint,py27,molecule
      python: "2.7"
    - name: py35
      python: "3.5"
      env: TOXENV=py35
    - name: py36
      python: "3.6"
      env: TOXENV=py36
    - name: py37
      python: "3.7"
      env: TOXENV=py37
    - stage: deploy
      name: deploy
      if: tag IS present AND type != cron
      env: TOXENV=upload
script:
  - travis_wait python -m tox

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - TRAVIS_NODE_VERSION="v8.11.3"
