
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-03T23:40:44+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "c04c09013db8286d7a6e843c1cf0390bc5fb36a4",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
