
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-01T13:36:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac3bda777611412ff4c24c87b386b4ac6bd0b4e5",
 "version": "0.8.2-alpha1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
