# coding: utf-8

"""
    Endpoints

    Endpoints API for different services in SKIL  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skil_client
from skil_client.models.resource import Resource  # noqa: E501
from skil_client.rest import ApiException


class TestResource(unittest.TestCase):
    """Resource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResource(self):
        """Test Resource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skil_client.models.resource.Resource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
