# coding: utf-8

"""
    Endpoints

    Endpoints API for different services in SKIL  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skil_client
from skil_client.models.add_example_request import AddExampleRequest  # noqa: E501
from skil_client.rest import ApiException


class TestAddExampleRequest(unittest.TestCase):
    """AddExampleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddExampleRequest(self):
        """Test AddExampleRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skil_client.models.add_example_request.AddExampleRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
