
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-27T16:13:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf09999a1281b457e07d901b4b082cb189bb6936",
 "version": "v0.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
