# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BleroGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='blero_grid_client_blerogrid', serialize=False, to='cms.CMSPlugin')),
                ('grid_label', models.CharField(max_length=200)),
                ('grid_columns', models.CharField(max_length=200)),
                ('grid_rows', models.CharField(max_length=200)),
                ('content_edited', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GridCells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_edited', models.BooleanField(default=False)),
                ('format_edited', models.BooleanField(default=False)),
                ('row_number', models.CharField(max_length=200, null=True)),
                ('column_number', models.CharField(max_length=200, null=True)),
                ('cell_content', models.CharField(max_length=200, null=True)),
                ('cell_font', models.CharField(max_length=200, null=True)),
                ('cell_font_size', models.CharField(max_length=200, null=True)),
                ('cell_font_color', models.CharField(max_length=200, null=True)),
                ('cell_background_color', models.CharField(max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='blero_grid_client.BleroGrid')),
            ],
        ),
        migrations.CreateModel(
            name='GridColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_edited', models.BooleanField(default=False)),
                ('format_edited', models.BooleanField(default=False)),
                ('column_number', models.CharField(max_length=200, null=True)),
                ('column_content', models.CharField(max_length=200, null=True)),
                ('column_font', models.CharField(max_length=200, null=True)),
                ('column_font_color', models.CharField(max_length=200, null=True)),
                ('column_background_color', models.CharField(max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='blero_grid_client.BleroGrid')),
            ],
        ),
        migrations.CreateModel(
            name='GridRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_edited', models.BooleanField(default=False)),
                ('format_edited', models.BooleanField(default=False)),
                ('row_number', models.CharField(max_length=200, null=True)),
                ('row_content', models.CharField(max_length=200, null=True)),
                ('row_font', models.CharField(max_length=200, null=True)),
                ('row_font_color', models.CharField(max_length=200, null=True)),
                ('row_background_color', models.CharField(max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='blero_grid_client.BleroGrid')),
            ],
        ),
        migrations.CreateModel(
            name='PluginPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resized', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=50, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('top', models.CharField(max_length=50, null=True)),
                ('left', models.CharField(max_length=50, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blero_grid_client.BleroGrid')),
            ],
        ),
    ]
