from bytegain.custom.cust.apartmentlist.feature_filter import FeatureFilter
EXCLUDED_FEATURES = [
    'interest_state',
    'final_interest_state',
    'viewed_availability',
    'dwell_time',
    'user_category_order',
    'photo_gallery_views',
    'user_order',
    'matched_user',
    'matched_interest',
    'opened_email',
    'email_opens_count',
    'email_clicks_count',
    'matching_units',
    'all_price',
    'availability_views',
    'commute_congestion',
    'preferences_amenities',
    'preferences_beds',
    'score',
    'interest_id',
    'leased_at_notified_property',
    'matched_user',
    'commute_lat',
    'commute_lon',
    'source_app',
    'median_matching_price',
    'photo_gallery_views',
    'prev_interests',
    'consent_call_consent',
    'consent_email_consent',
    'preferences_contracts',
    'renter_phone_area_code',
    'renter_phone_exchange',
    'interest_created_at',
    'total_units',
    'matched_interest',
    'user_id',

    'preferences_wants_dishwasher',
    # 'preferences_most_important_feature',
    # 'preferences_wants_on_site_laundry',
    # 'preferences_wants_gym',
    # 'preferences_wants_in_unit_laundry',
    'preferences_wants_dog_friendly',
    # 'preferences_wants_pool',
    # 'preferences_wants_air_conditioning',
    # 'preferences_wants_parking',
    'preferences_cotenant',
    'preferences_cosigner',
    'avg_12mo_2bd_location_price',
    'relative_2bd_price',

    # 'preferences_baths',
    # 'preferences_beds_0',
    # 'preferences_beds_1',
    #'preferences_beds_2',
    # 'preferences_beds_3',
    'has_phone_number',
    'email_clicked',
    # 'commute_mode',
    'registered_source_app',
    'relative_positive_velocity_rate',
    'property_to_total_velocity_rate',
    'positive_interest_velocity',
    # 'positive_velocity_rate',
    'total_interest_velocity',
    'property_lat',
    'property_lon',
    'search_sort_variation',
    'best_bets_variation',
]

NUMERICAL_FEATURES = [
    'preferences_lease_length',
    'preferences_move_urgency',
    'metro_price',
]

CATEGORY_FEATURES = [
]

BUCKET_FEATURES = [
    # 'interest_source_app',
    # 'search_category',
    # 'metro_id',
    # 'commute_mode',
    # 'preferences_most_important_feature',
    # 'preferences_wants_on_site_laundry',
    # 'preferences_wants_gym',
    # 'preferences_wants_in_unit_laundry',
    # 'preferences_wants_dog_friendly',
    # 'preferences_wants_pool',
    # 'preferences_wants_air_conditioning',
    # 'preferences_wants_parking',
]

filter = FeatureFilter(EXCLUDED_FEATURES, NUMERICAL_FEATURES, CATEGORY_FEATURES, BUCKET_FEATURES)
