language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install coverage coveralls
    - pip install zope.testrunner flake8
    - pip install Sphinx repoze.sphinx.autointerface zope.app.wsgi
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src -v
    - flake8 src setup.py --doctests
    - sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html
    - sphinx-build -b doctest -d docs/_build/doctrees docs docs/_build/doctest
after_success:
    - coveralls
notifications:
    email: false
cache: pip
