language: python
python:
  - 2.7

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -q

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - bin/test
  - bin/coverage.sh
  - bin/code-analysis

after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    recipients:
      - devs@imio.be
    on_success: change
    on_failure: change

