language: c

sudo: false

os:
  - linux
  - osx

notifications:
  email: false

env:
  global:
    - SETUP_XVFB=True
    - CONDA_CHANNELS="glueviz"
    - CONDA_DEPENDENCIES="glue-core pytest mock requests pydicom gdcm nomkl"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=2.7 CONDA_CHANNELS="glueviz glueviz/label/dev"
    - PYTHON_VERSION=3.5 CONDA_CHANNELS="glueviz glueviz/label/dev"

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

  # The gdcm conda package does not work well on MacOS X with Python 3.x.
  # Unfortunately there isn't much we can do about it.
  # https://github.com/conda-forge/gdcm-feedstock/issues/8
  - if [[ $PYTHON_VERSION == 3.* && $TRAVIS_OS_NAME == osx ]]; then conda remove --no-pin gdcm; fi

script:
  - py.test glue_medical
