#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['rnumpy']

package_data = \
{'': ['*']}

install_requires = \
['numpy >= 1.16.4']

extras_require = \
{'doc': ['sphinx'], 'test': ['pytest']}

setup(name='rnumpy',
      version='0.0.1',
      description='RNumPy',
      author='Ralf Gommers',
      author_email='ralf.gommers@gmail.com',
      url='https://github.com/Quansight-Labs/rnumpy',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
