# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_auto_20190204_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glossary.Campus', verbose_name='Корпус'),
            preserve_default=False,
        ),
    ]
