# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_room_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Административное'), (2, 'Образовательное')], default=1, verbose_name='Тип структурного подразделения'),
        ),
    ]
