language: c

sudo: false

notifications:
  email: false

env:
  global:
    - COMMAND="pytest glue_vispy_viewers --cov glue_vispy_viewers"
    - SETUP_XVFB=True
    - CONDA_CHANNELS="glueviz"
    - CONDA_DEPENDENCIES="glueviz mock pyopengl pyqt pytest-cov qtpy scipy"
    - CONDA_CHANNEL_PRIORITY=True
    - PIP_DEPENDENCIES="pytest-qt objgraph"
  matrix:
    - PYTHON_VERSION=3.5 CONDA_DEPENDENCIES="" PIP_DEPENDENCIES="flake8" COMMAND="flake8 --max-line-length=100 --exclude=extern glue_vispy_viewers"
    # - PYTHON_VERSION=2.7
    # - PYTHON_VERSION=3.5
    - PYTHON_VERSION=2.7 CONDA_CHANNELS="glueviz/label/dev"
    - PYTHON_VERSION=3.5 CONDA_CHANNELS="glueviz/label/dev"

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - if [[ $COMMAND == pytest* ]]; then pip install coveralls; fi

script:
  - $COMMAND

after_success:
  - if [[ $COMMAND == pytest* ]]; then coveralls; fi
