
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.20.1.post1',
    'branch_nick': '(HEAD',
    'revision_id': 'eacfc65cd7db4f6eaa2a181db0f9afed22b314b7',
    'revno': 8316
}
