
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-25T22:17:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f212c08d31299e558cc87947b8082361d348ee62",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
