[tool.poetry]
name = "waldcli"
version = "0.2.2"
description = "The waldemar client for web projects (using docker)"
authors = ["andrea giacobino <no.andrea@gmail.com>", "enrico icardi <enrico@welance.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/welance/internal/waldcli"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2"
PyYAML = "3.13"
colorama = "^0.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"

[tool.poetry.scripts]
waldcli = "waldcli.butler:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


