SERVICE_ACCEPTS: .*
SERVICE_REJECTS: empty|metadata/.*

SERVICE_CATEGORY: Uncategorized
SERVICE_CLASSIFICATION: U
SERVICE_DEFAULT_CONFIG: {}
SERVICE_DEFAULT_SUBMISSION_PARAMS: []
SERVICE_DESCRIPTION: N/A
SERVICE_DISABLE_CACHE: false
SERVICE_ENABLED: false
SERVICE_LICENCE_COUNT: 0
SERVICE_REVISION: '0'
SERVICE_SAVE_RESULT: true
SERVICE_SAFE_START: false
SERVICE_STAGE: CORE
SERVICE_SUPPORTED_PLATFORMS: [Linux]
SERVICE_TIMEOUT: 60
SERVICE_VERSION: '0'
SERVICE_IS_EXTERNAL: false

SERVICE_CPU_CORES: 1
SERVICE_RAM_MB: 1024
