dist: xenial
sudo: false
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: wayfair
  password:
    secure: PN+whl6J77UsV1hvMQSSTcKHAlPAWN9L4ZDlXfqc4l0+jvcjmlXryOpxS6NXY6Q+qXpLgoo1adT92jmH+zk+S4Ix3xYnufpWd/HkHnPXbPxNXrFbVnNbbAOgfNwMBJESgWoR7Y5Suco0oPOZpTPaaH1GaLrt6n+3TSnWLvQn+ar/m2pcTqHC05N6SLI3t3oOiN0kHkvpLLTue7Apr8OPQZuVVpy7KOs6mx9jDiTzG0qcwZr20gKLx4BBSklDOW7WurRwcMOZ9LHfbmP5TwRlLYc77ujGdtz83X02bglCHc0VFxckknEx7antJ0BeURdWv6XKEVrcOAFEX97kk86YmjWIDP/ei+MVa9FKXb6AvCwpk+QpkG7UHJYSgijJuQxNqCGwQ6/JnDziCfH0AK2IGuB45jR2uG7wmQ/5iM5UJ30QAGoOXta88RlqwNboB9rR7h4UB2KjW/EcWCiEJb8cPXZsXRxFW9XqG390ZsrcHdpElpJKuqHAqX3gavuEI86Dc8rB36JdI3BGMr+TC9Edb4SRQsWiHHKBeeLUXqKoGgVkshivzbqBP7/emx5UobqHHKcnFgsCk/xsxIqM59PiAFIc2+fUhHtRjV2WEuMtQ6B8T3KXFrMoX8/BlUy8A5gTeA+0weRb70Grxn8eIOfDq7t6c07YswJP2OSVIRyTosU=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    repo: wayfair/pytest-eucalyptus
    branch: master