# Generated by Django 2.1.7 on 2019-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0018_clusteroperation_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteroperation',
            name='auto',
            field=models.BooleanField(default=True, verbose_name='auto run'),
        ),
        migrations.AlterField(
            model_name='clusteroperation',
            name='instances',
            field=models.ManyToManyField(blank=True, editable=False, to='clouds.Instance'),
        ),
    ]
