# Generated by Django 2.1.7 on 2019-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0021_auto_20190411_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteroperation',
            name='broadcast',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='clusteroperation',
            name='manual',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
