environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"
      NUMPY: "numpy>=1.15"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"
      NUMPY: "numpy>=1.15"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy>=1.15"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NUMPY: "numpy>=1.15"

install:
  - "python --version"

build_script:
  - "pip install %NUMPY%"
  - "pip install awkward>=0.8.0,<0.9.0"
  - "pip install uproot-methods>=0.4.0,<0.5.0"
  - "pip install -i https://pypi.anaconda.org/carlkl/simple backports.lzma"
  - "pip install pytest pytest-runner pandas requests"
  - "python setup.py pytest"
