image: Visual Studio 2017

environment:
  global:
    CIBW_SKIP: cp33-* cp34-* cp35-* cp37-* cp27-win_amd64 cp36-win32
    # CIBW_TEST_REQUIRES: pytest subprocess32
    # CIBW_TEST_COMMAND: cd {project} && pytest -v && pip uninstall --yes afdko
    TWINE_USERNAME: adobe-type-tools-ci
    # Note: TWINE_PASSWORD is set in AppVeyor settings

matrix:
  fast_finish: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# to run your custom scripts instead of automatic MSBuild
build_script:
  # our setup.py requires 'wheel', which may not be already installed
  - pip install git+https://github.com/adobe-type-tools/cibuildwheel wheel
  - cibuildwheel --output-dir wheelhouse

artifacts:
  # archive the generated packages in the ci.appveyor.com build report
  - path: wheelhouse\*.whl
    name: Wheels

on_success:
  # deploy wheels to PyPI on tags
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        python -m pip install twine
        python -m twine upload wheelhouse/*.whl
      }

deploy:
  # deploy wheels to GitHub on tags
  provider: GitHub
  auth_token:
    secure: UyKfsObr/shlpP+0U5Zb3EPvmXt0kyKYu940CFNFdNZ8J7Fu54k415R0UNP78t0j
  artifact: Wheels
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - afdko@adobe.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
