# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apptools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ImageButton',
            fields=[
                ('action', models.SlugField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptools.Icon')),
            ],
        ),
    ]
