language: python
python:
  - "3.6"

env:
  - CC="gcc"

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install
  - python setup.py build_ext --inplace

script:
  - poetry run green -v ./tests/test_unit
