# Generated by Django 2.2 on 2019-05-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190521_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainstance',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Cluster'),
        ),
    ]
