# Generated by Django 2.2.2 on 2019-07-04 14:14

from django.db import migrations, models
import znbdownload.fields


class Migration(migrations.Migration):

    dependencies = [
        ('znbdownload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('private_file', znbdownload.fields.S3PrivateFileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
