# Generated by Django 2.2.2 on 2019-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_roadtrip', '0002_auto_20190619_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='capacité du réservoir'),
        ),
    ]
