#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['submark']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['submark = submark:main']}

setup(name='submark',
      version='0.6',
      description='A Subset of Markdown',
      author='Brian Okken',
      author_email='',
      url='https://github.com/okken/submark',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
