
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-27T20:08:28+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "517c3632de91157fe4236a981da6dd17049fee3b",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
