# Generated by Django 2.2 on 2019-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0049_auto_20190428_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
