[tool.poetry]
name = "cosilico-runner"
version = "0.1.0"
description = ""
authors = ["Erik Storrs <epstorrs@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
cosilico-runner = 'cosilico_runner:cosilico_runner.main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
