
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-26T23:08:18+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "748ae635e6f4924c49c98a82b35b0c09a99bba92",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
