[tool.poetry]
name = "libpyrite"
version = "0.1.0-alpha.1"
description = "PyTorch utility library"
authors = ["Miller Wilt <miller@pyriteai.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.5"
torch = "^1.1"
torchvision = "^0.3.0"
tqdm = "^4.32"
scipy = "^1.3"

[tool.poetry.dev-dependencies]
mypy = "^0.701.0"
pylint = "^2.3"
pytest = "^4.5"
black = {version = "^18.3-alpha.0",allows-prereleases = true,python = "^3.6"}
pre-commit = "^1.16"
ipython = "^7.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
