# coding: utf-8

"""
    ACA Services API

    API for methods pertaining to all ACA services  # noqa: E501

    OpenAPI spec version: 1.4.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import autocheckauctions
from autocheckauctions.api.batch_api import BatchApi  # noqa: E501
from autocheckauctions.rest import ApiException


class TestBatchApi(unittest.TestCase):
    """BatchApi unit test stubs"""

    def setUp(self):
        self.api = autocheckauctions.api.batch_api.BatchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_accident(self):
        """Test case for batch_accident

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_announcement(self):
        """Test case for batch_announcement

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_canadian(self):
        """Test case for batch_canadian

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_canadian_plus(self):
        """Test case for batch_canadian_plus

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_compromised(self):
        """Test case for batch_compromised

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_disaster(self):
        """Test case for batch_disaster

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_discrepancy(self):
        """Test case for batch_discrepancy

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_exception(self):
        """Test case for batch_exception

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_full(self):
        """Test case for batch_full

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_recall(self):
        """Test case for batch_recall

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_retrieve(self):
        """Test case for batch_retrieve

        Retrieve Presigned URL  # noqa: E501
        """
        pass

    def test_batch_summary(self):
        """Test case for batch_summary

        Retrieve Batch Token  # noqa: E501
        """
        pass

    def test_batch_theft(self):
        """Test case for batch_theft

        Retrieve Batch Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
