---
- hosts: undercloud
  vars:
    metadata:
      name: Verify existence of deployment images
      description: >
        This validation checks that images bm-deploy-kernel and
        bm-deploy-ramdisk exist before deploying the overcloud,
        and that only one exists by that name.
      groups:
      - pre-deployment
      - pre-upgrade
    deploy_kernel_name: "bm-deploy-kernel"
    deploy_ramdisk_name: "bm-deploy-ramdisk"
  roles:
    - deployment-images
