environment:
  matrix:
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python35-x64"
  - PYTHON: "C:\\Python37-x64"

install:
# symlink python from a directory with a space
- "mklink /d \"C:\\Program Files\\Python\" %PYTHON%"
- "SET PYTHON=\"C:\\Program Files\\Python\""
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- "python -m pip install tox"


before_build:
- "python -m pip install wheel"

build_script:
- python -m setup bdist_wheel

test_script:
- tox

on_finish:
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\.test-results\pytest\results.xml))

#deploy_script:
#- ps: >-
#    if($env:appveyor_repo_tag -eq 'True') {
#        Invoke-Expression "python -m twine upload dist/* --username $env:PYPI_USERNAME --password $env:PYPI_PASSWORD"
#    }

artifacts:
- path: dist\*
