# Generated by Django 2.1.7 on 2019-04-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0028_group_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='hosts',
        ),
    ]
