language: python
dist: xenial
sudo: false

matrix:
    include:
        - python: "3.4"
          env: REQUIRES=normal
        - python: "3.5"
          env: REQUIRES=normal
        - python: "pypy3.5"
          env: REQUIRES=normal
        - python: "3.6"
          env: REQUIRES=normal
        - python: "3.6"
          env: REQUIRES=minimum
        - python: "3.7"
          env: REQUIRES=normal

install:
    - if [ "$REQUIRES" = minimum ]; then tools/minimum_requires.sh; fi
    - pip install -e .
    - pip install -r tools/requirements.txt

cache: pip

script:
    # Make sure there are no "FIXME" marks in the codebase.
    - test ! "$( git grep -l FIXME | grep -Fv .travis.yml )"

    # Basic stuff.
    - python setup.py check --strict --restructuredtext
    - pylint -j 2 --reports=no --score=no *.py **/*.py
    - pytest

    # Although the main docs (``doc/``) are processed by Read the Docs,
    # we want to check that they are building OK.
    # Also, make sure that the included API example works.
    - python doc/api_example.py && grep -q 1194 report.html
    - sphinx-build -W doc/ doc/_build/

    # Check the assorted reStructuredText documents at the top of the repo.
    - tools/check_rst.sh

    # Check that the source distribution includes everything it should,
    # and nothing it shouldn't (including all the files we just built).
    - check-manifest

deploy:
    on:
        tags: true
        # Only release from one of the environments.
        python: "3.6"
        condition: $REQUIRES = normal
    provider: pypi
    user: vfaronov
    password:
        secure: Ym1VrWn+vEEumSVT3rIXk5qz/EtEYht/9KnQwi9zW2kkJ40DRcITq19AxAhCcKeW+wut/Q9gk5dmAKVbudIJCvd7r1pG+XOQuvoJS7xpua7+uunDs56vZwhcNrQumzluoBxSYDpTUjc0xey2vcWacjQViqTLYMFu97sfFTmfQuvRD6/7u83ZsyU7ixweTm+XpCpL72MfJMZo/pFEL+d4fg8stXyboPWzMA9tKh2uk4i7TD1iWcPDfisKDwhqz6F/SN66P7ylmz69h/plwPCncUCXUR6ovbWDYqyE845Awrwd+VylGkrmTMC2FQb14TR2LQStYr0XwcM0aftQDJkoYscnmf01OCreZrs5hwbY8xrF7Jill47ueDrGXtH6FwgcZBgTscdoR+F92IINOZcuKzrOToGZPZsi7la3hrdltCSMbV9npO4M5z7By8IrUSV/DsnupF/+RsTNA1I65IEyhlC0V1xv0cQUi+/DNe6UDebHXRR6qNt1oXgDDogK60s5x28srPKBW9JRmXM7M61II2di19WV83dvwtsiqGZ/WUDVtO1mzMcnSnuep4KLhP21FhtKRIj/g6YMwiYVqGVBsluJecV/tmHVUtSXjE/L9myowq1mFVmew3lc6p2n9OjVfbn2PplnwbKm781/9YX30r7aR9NPNquBB1RVhlIn4qE=
    distributions: "sdist bdist_wheel"
    skip_upload_docs: true
