
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-28T00:49:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "22f4e52a5db1850984e39432f126356fb65bb0dd",
 "version": "0.1.5b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
