# coding: utf-8

"""
    ACA Services API

    API for methods pertaining to all ACA services  # noqa: E501

    OpenAPI spec version: 1.4.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VehicleRequestAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dealer_number': 'str',
        'reference_number': 'str',
        'sale_number': 'str',
        'vin': 'str'
    }

    attribute_map = {
        'dealer_number': 'dealerNumber',
        'reference_number': 'referenceNumber',
        'sale_number': 'saleNumber',
        'vin': 'vin'
    }

    def __init__(self, dealer_number=None, reference_number=None, sale_number=None, vin=None):  # noqa: E501
        """VehicleRequestAttribute - a model defined in Swagger"""  # noqa: E501

        self._dealer_number = None
        self._reference_number = None
        self._sale_number = None
        self._vin = None
        self.discriminator = None

        if dealer_number is not None:
            self.dealer_number = dealer_number
        if reference_number is not None:
            self.reference_number = reference_number
        if sale_number is not None:
            self.sale_number = sale_number
        self.vin = vin

    @property
    def dealer_number(self):
        """Gets the dealer_number of this VehicleRequestAttribute.  # noqa: E501

        the dealer number assigned by the auction  # noqa: E501

        :return: The dealer_number of this VehicleRequestAttribute.  # noqa: E501
        :rtype: str
        """
        return self._dealer_number

    @dealer_number.setter
    def dealer_number(self, dealer_number):
        """Sets the dealer_number of this VehicleRequestAttribute.

        the dealer number assigned by the auction  # noqa: E501

        :param dealer_number: The dealer_number of this VehicleRequestAttribute.  # noqa: E501
        :type: str
        """

        self._dealer_number = dealer_number

    @property
    def reference_number(self):
        """Gets the reference_number of this VehicleRequestAttribute.  # noqa: E501

        the reference number for the caller's tracking purposes  # noqa: E501

        :return: The reference_number of this VehicleRequestAttribute.  # noqa: E501
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """Sets the reference_number of this VehicleRequestAttribute.

        the reference number for the caller's tracking purposes  # noqa: E501

        :param reference_number: The reference_number of this VehicleRequestAttribute.  # noqa: E501
        :type: str
        """

        self._reference_number = reference_number

    @property
    def sale_number(self):
        """Gets the sale_number of this VehicleRequestAttribute.  # noqa: E501

        the lane assignment and run number assigned to the vehicle from the auction  # noqa: E501

        :return: The sale_number of this VehicleRequestAttribute.  # noqa: E501
        :rtype: str
        """
        return self._sale_number

    @sale_number.setter
    def sale_number(self, sale_number):
        """Sets the sale_number of this VehicleRequestAttribute.

        the lane assignment and run number assigned to the vehicle from the auction  # noqa: E501

        :param sale_number: The sale_number of this VehicleRequestAttribute.  # noqa: E501
        :type: str
        """

        self._sale_number = sale_number

    @property
    def vin(self):
        """Gets the vin of this VehicleRequestAttribute.  # noqa: E501

        the vehicle identification number  # noqa: E501

        :return: The vin of this VehicleRequestAttribute.  # noqa: E501
        :rtype: str
        """
        return self._vin

    @vin.setter
    def vin(self, vin):
        """Sets the vin of this VehicleRequestAttribute.

        the vehicle identification number  # noqa: E501

        :param vin: The vin of this VehicleRequestAttribute.  # noqa: E501
        :type: str
        """
        if vin is None:
            raise ValueError("Invalid value for `vin`, must not be `None`")  # noqa: E501

        self._vin = vin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VehicleRequestAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
