PARAM_ID_CURRENT_KP: 3110
PARAM_ID_CURRENT_KI: 2800
PARAM_ID_CURRENT_MAX_ITERM: 268427264
PARAM_ID_CURRENT_MIN_ITERM: -268427264
PARAM_ID_CURRENT_MAX_LIMIT: 4000
PARAM_ID_CURRENT_MIN_LIMIT: -4000

PARAM_ID_VELOCITY_KP: 600
PARAM_ID_VELOCITY_KI: 80
PARAM_ID_VELOCITY_KD: 10
PARAM_ID_VELOCITY_MAX_ITERM: 90000000
PARAM_ID_VELOCITY_MIN_ITERM: -90000000
PARAM_ID_VELOCITY_MAX_LIMIT: 5000
PARAM_ID_VELOCITY_MIN_LIMIT: -5000

PARAM_ID_POSITION_KP: 100
PARAM_ID_POSITION_KI: 10
PARAM_ID_POSITION_KD: 5
PARAM_ID_POSITION_MAX_ITERM: 50000
PARAM_ID_POSITION_MIN_ITERM: -50000
PARAM_ID_POSITION_MAX_LIMIT: 2147483647
PARAM_ID_POSITION_MIN_LIMIT: -2147483648

PARAM_ID_POSITION_OFFSET: 0 