
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-02T00:34:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9c13b04b46aae44fc6d340e88ed0c4e546586ce",
 "version": "0.2.3b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
