# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline@16\couchbase-python-client\couchbase_version.py
# at
#    2019-07-05 11:38:06.205205
__version__ = '3.0.0a3'