
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-19T13:34:28+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1b4527a7c98caa1ecfab01a5cf0b293ca7495b5",
 "version": "0.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
