/* Generated by Cython 0.24.1 */

#ifndef __PYX_HAVE__VirtualMicrobes__cython_gsl_interface__odes
#define __PYX_HAVE__VirtualMicrobes__cython_gsl_interface__odes

struct mol_str;

/* "VirtualMicrobes/cython_gsl_interface/odes.pxd":169
 * #------------------------ **SMALL MOLECULES** -------------------------#
 * 
 * cdef public struct mol_str:             # <<<<<<<<<<<<<<
 *     int variable
 *     double degr_const
 */
struct mol_str {
  int variable;
  double degr_const;
  double diff_const;
  double influx_const;
  double toxic_level;
  int diff_external_var;
  double grid_diffusion_force;
  __Pyx_memviewslice time_concentration_vector;
  __Pyx_memviewslice time_change_rate_vector;
};

#ifndef __PYX_HAVE_API__VirtualMicrobes__cython_gsl_interface__odes

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__VirtualMicrobes__cython_gsl_interface__odes */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initodes(void);
#else
PyMODINIT_FUNC PyInit_odes(void);
#endif

#endif /* !__PYX_HAVE__VirtualMicrobes__cython_gsl_interface__odes */
