# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-03 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_mission', '0016_userstage_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['id'], 'permissions': (('can_manage_mission', '\u53ef\u4ee5\u8fdb\u5165mission\u7ba1\u7406\u9875'), ('view_index_mission', '\u53ef\u4ee5\u8fdb\u5165\u9996\u9875\u4efb\u52a1\u677f\u5757'))},
        ),
    ]
