sudo:
  false

language:
  python

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

matrix:
  include:
    - env: TOXENV=lint

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - pip install tox coveralls

script:
  - make test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: fF4lcMoigcCNec0AKEgurNrbqjUDZUw9ISo1EMtlMfogy/3dq4Oc6u/Ees1CXt+BUQ0R4iPpdc5DtN2w1qQ9ToYIX4did4C0Y67OS/K+Jo3aQ+lWROjpn9oAOVyE9VqDAJAXC6kjGfEmIXIQW+qS4JjKb5dW0Fq0FAitWLXHzYk=
