dist: xenial
services: docker
language: python

python:
- 2.7
- 3.5
- 3.6
- 3.7

before_install:
# Conda install for Travis, taken from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a
- conda install --no-update-deps -y -c vincent-noel maboss
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install coveralls
- docker run -p 7777:7777 --network host -d vnoel/maboss-server

install:
- pip install .

script:
- coverage run -m unittest discover -v

after_script:
- coveralls
