# coding: utf-8

"""
    VXC Services API

    API for methods pertaining to all VXC services  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vincrosscheck
from vincrosscheck.models.request1 import Request1  # noqa: E501
from vincrosscheck.rest import ApiException


class TestRequest1(unittest.TestCase):
    """Request1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequest1(self):
        """Test Request1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vincrosscheck.models.request1.Request1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
