# coding: utf-8

"""
    VXC Services API

    API for methods pertaining to all VXC services  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vincrosscheck
from vincrosscheck.api.brick_ftp_api import BrickFTPApi  # noqa: E501
from vincrosscheck.rest import ApiException


class TestBrickFTPApi(unittest.TestCase):
    """BrickFTPApi unit test stubs"""

    def setUp(self):
        self.api = vincrosscheck.api.brick_ftp_api.BrickFTPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_brickftp(self):
        """Test case for brickftp

        Webhook for VXC BrickFTP implementations  # noqa: E501
        """
        pass

    def test_brickftp_0(self):
        """Test case for brickftp_0

        Webhook for VXC compressed file transfer  # noqa: E501
        """
        pass

    def test_brickftp_1(self):
        """Test case for brickftp_1

        Webhook for VXC encrypted file transfer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
