# coding: utf-8

"""
    OOXML Automation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import presalytics_ooxml_automation
from presalytics_ooxml_automation.models.chart_axis_data_types import ChartAxisDataTypes  # noqa: E501
from presalytics_ooxml_automation.rest import ApiException


class TestChartAxisDataTypes(unittest.TestCase):
    """ChartAxisDataTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChartAxisDataTypes(self):
        """Test ChartAxisDataTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = presalytics_ooxml_automation.models.chart_axis_data_types.ChartAxisDataTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
