# coding: utf-8

"""
    OOXML Automation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import presalytics_ooxml_automation
from presalytics_ooxml_automation.models.shared_line_end_types import SharedLineEndTypes  # noqa: E501
from presalytics_ooxml_automation.rest import ApiException


class TestSharedLineEndTypes(unittest.TestCase):
    """SharedLineEndTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSharedLineEndTypes(self):
        """Test SharedLineEndTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = presalytics_ooxml_automation.models.shared_line_end_types.SharedLineEndTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
