# Generated by Django 2.1.7 on 2019-04-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0012_clusteroperation_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='hosts',
        ),
    ]
