# Generated by Django 2.2 on 2019-04-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0041_auto_20190418_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepoperation',
            options={'ordering': ['-started_time', '-pk'], 'verbose_name': 'operation'},
        ),
    ]
