# Generated by Django 2.2.2 on 2019-07-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_geobase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipcodeRussianPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zipcode')),
                ('geobase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_tasker_geobase.Geobase')),
            ],
        ),
    ]
