# Generated by Django 2.2.2 on 2019-07-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_geobase', '0002_zipcoderussianpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZipcodeRussianPost',
            new_name='ZipodePostOffice',
        ),
    ]
