# -*- coding: utf-8 -*-
from distutils.core import setup

packages = \
['smrt',
 'smrt.atmosphere',
 'smrt.core',
 'smrt.emmodel',
 'smrt.inputs',
 'smrt.interface',
 'smrt.microstructure_model',
 'smrt.permittivity',
 'smrt.rtsolver',
 'smrt.substrate',
 'smrt.utils']

package_data = \
{'': ['*'],
 'smrt': ['speed_test/*',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/README',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtdort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_dmrtodort.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_iba_sea_ice.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_iba_original.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_integration_oiba.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_mixed_emmodel.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_model.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_physics_law.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py',
          'test/test_soil_odort.py']}

install_requires = \
['numpy>=1.13', 'pandas>=0.20.3', 'scipy>=1.0.0', 'six>=1.0', 'xarray>=0.10.3']

setup_kwargs = {
    'name': 'smrt',
    'version': '1.0.2',
    'description': 'The Snow Microwave Radiative Transfer (SMRT) model is a highly modular model to compute the thermal emission of snowpacks and other cryospheric bodies in the microwave domain.',
    'long_description': None,
    'author': 'Ghislain Picard',
    'author_email': 'ghislain.picard@univ-grenoble-alpes.fr',
    'url': 'https://www.smrt-model.science/',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.5',
}


setup(**setup_kwargs)
