
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-01T20:55:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "df5499d0bba51b11aafe915276d9be6882d65a48",
 "version": "0.2.1b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
