# CI on Windows via appveyor
# This file is based on xarray, which is in turn based on
# Olivier Grisel's python-appveyor-demo
branches:
  except:
    - fix-docs

environment:

  matrix:
    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py36-windows"
    - PYTHON: "C:\\Python37-conda64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py37-windows"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # install xarray and dependencies
  - "conda env create --file ./ci/requirements-%CONDA_ENV%.yml"
  - "activate test_env"
  - "conda list"
  - "python -m pip install . --no-deps -vv"

build: false

test_script:
  - "pytest --pyargs climlab.tests --verbose"
