
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-06T17:59:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f308b90f03b1abc8015bfd72785b8e41484238b",
 "version": "0.10.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
