
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-05T08:32:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9afb3a7dd27e0caae42740f09bdfad48ce47315",
 "version": "0.2.3b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
