[tool.poetry]
name = "peakipy"
version = "0.1.19"
description = "Deconvolute overlapping NMR peaks"
authors = ["Jacob Brady <jacob.brady0449@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.24.0"
numpy = "^1.16"
matplotlib = "^3.0"
PyYAML = "^5.1"
nmrglue = "^0.6.0"
scipy = "^1.2"
docopt = "^0.6.2"
lmfit = "^0.9.12"
scikit-image= "^0.14.2"
bokeh = "^1.0.4"
schema = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
peakipy = 'peakipy.__main__:main'
