# Generated by Django 2.1.7 on 2019-04-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0019_auto_20190412_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceoperation',
            name='log',
            field=models.TextField(blank=True, editable=False, max_length=51200, null=True),
        ),
    ]
