# Generated by Django 2.1.7 on 2019-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0023_remove_instance_remedy_script_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='remedy_script_todo',
            field=models.TextField(blank=True, default='', max_length=51200),
        ),
    ]
