
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-02T16:27:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "39eca6287ed12a97115b8d47a15522e69f7bc604",
 "version": "2.0.0-beta.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
