
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-01T10:03:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1562466856864e9f33d9f412a102deaeaaba4a7",
 "version": "4.0.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
