# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

      CONDA_CHANNELS: "glueviz"
      CONDA_DEPENDENCIES: "glue-core rasterio pyproj mock"

  matrix:

        # We have to pin PyQt5 to a specific build with Python 2.7 to avoid
        # segmentation faults with pyqt=5.6.0=py27_2
      - PYTHON_VERSION: "2.7"
        CONDA_DEPENDENCIES: "glue-core rasterio pyproj pyqt=5.6.0=py27h6e61f57_6"
      - PYTHON_VERSION: "2.7"
        CONDA_DEPENDENCIES: "glue-core rasterio pyproj pyqt=5.6.0=py27h6e61f57_6"
        CONDA_CHANNELS: "glueviz/label/dev"

      - PYTHON_VERSION: "3.6"
      - PYTHON_VERSION: "3.6"
        CONDA_CHANNELS: "glueviz/label/dev"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

build: false

test_script:
  - "%CMD_IN_ENV% py.test glue_geospatial"
