language: python
dist: xenial
group: travis_latest
services:
  - mysql
  - postgresql
  - memcached
addons:
# Use postgresql 9.3 to get commit-lock testing
# Use postgresql 9.4 to get support for BLOB SQL functions for pg8000
# Use postgresql 9.5 to get support for INSERT ON CONFLICT UPDATE
# Use postgresql 9.6 ... just because
  postgresql: "9.6"
# The default mysql is 5.7; we have a specific test for 8.0.

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3
    - python: 3.7
      services:
        - docker
        - postgresql
        - memcached
      before_install:
        - docker pull mysql:8.0
        - docker run -d --publish 3306:3306 --rm --name mysqld -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mysql:8.0
        - cp .travis/docker.cnf ~/.my.cnf
env:
    global:
        - PYTHONHASHSEED=8675309
        - CC="ccache gcc"
        - CCACHE_NOCPP2=true
        - CCACHE_SLOPPINESS=file_macro,time_macros,include_file_ctime,include_file_mtime
        - CCACHE_NOHASHDIR=true
        - CFLAGS="-g -pipe"

script:
# coverage slows PyPy down from 2minutes to 12+.
# But don't run the pymysql/pypy tests twice.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pylint --rcfile=.pylintrc relstorage -f parseable -r n; fi
  # Disable inlining right now. See https://github.com/zodb/relstorage/issues/228#issuecomment-492423284
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python --jit inlining=0 -m zope.testrunner --test-path=src --auto-color --auto-progress; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m  zope.testrunner --test-path=src --auto-color --auto-progress; fi
after_success:
  - coveralls
notifications:
  email: false

before_install:
  - python --version
before_script:
  - ccache -s
  - mysql -uroot -e 'select version()'

install:
  - pip install -U pip
  - pip install -U setuptools wheel coveralls
  - pip install -U "pylint>=1.7.1"
  - pip install -U 'cffi; platform_python_implementation=="CPython"'
  - pip install -U -e ".[test,all_tested_drivers]"
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install git+https://github.com/NextThought/umysqldb.git#egg=umysqldb; fi
  - .travis/postgres.sh
  - .travis/mysql.sh

cache:
  pip: true
  directories:
    - $HOME/.wheelhouse
    - $HOME/.ccache

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
