
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-10T10:10:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "05fc3d9c64a5f9ff701f9d9541f707aff5750349",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
