[tool.poetry]
name = "lobio"
version = "0.0.12"
description = "Extra utilities for BioPython"
authors = ["Justin Vrana <justin.vrana@gmail.com>"]
homepage = "https://www.github.com/jvrana/LoBio"
repository = "https://www.github.com/jvrana/LoBio"
documentation = "https://www.github.com/jvrana/LoBio"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.7"
biopython = "^1.73"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^4.6"
pre-commit = "^1.17"
toml = "^0.10.0"
keats = "^0.2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
