---
coverage:
  status:
    project:
      default: false
      tests:
        target: 100%
        paths: "tests/"
      app:
        target: 95%
        paths: "src/"
    patch:
      default:
        target: 95%
        threshold: 2%
...
