---
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install twine tox flake8 codecov python-semantic-release

codecov:
  stage: test
  script:
    - tox -e coverage
    - codecov --token=673d3fbf-c00a-49f6-871c-c5b8a12ba89e

linting:
  stage: test
  script:
    - tox -e black, yamllint, flake8

deploy_production:
  stage: deploy
  variables:
    PYPI_USERNAME: $PRODUCTION_USERNAME
    PYPI_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - python setup.py bdist bdist_wheel
    - git config --global user.name "semantic-release (via GitlabCI)"
    - git config --global user.email "semantic-release@gitlab-ci"
    - semantic-release publish
    - semantic-release changelog >> changelog.md
  artifacts:
    paths:
      - build/*
      - changelog.md

python35:
  image: python:3.5
  stage: test
  script: tox -e py35

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  stage: test
  script: tox -e py37
...
