
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-05T13:07:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1730819b4e3d76249541268e4d880c5eaa44498",
 "version": "0.1.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
