sudo: false
language: python
dist: trusty
python:
- 3.5
- 3.6
services:
- rabbitmq
install:
- pip install -r requires/testing.txt -r docs/requirements.txt codecov
script:
- nosetests
after_success:
- codecov
- ./setup.py build_sphinx
deploy:
  provider: pypi
  user: sprockets
  distributions: sdist bdist_wheel
  password:
    secure: IJVu1MUk2NtRprWkYL+prPRbWrDdSiP+L06S6xERqYnu+fy1ez8/zODazkQGKagXAAujbJK8OwyCgoMzCGDNHV3/NfFtz9dirGVAD2rXZ6AVfHjtEh31L2b2YzXEK0EnBMRsYRjsqLva6q7tfxzjMWKFria25wsd9bN8VlofNDQ=
  on:
    python: 3.6
    tags: true
    repo: sprockets/sprockets.mixins.amqp
