# Generated by Django 2.2.2 on 2019-06-28 04:02

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djcommerce', '0003_auto_20190627_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('complete', 'Complete'), ('originated', 'Originated'), ('pending', 'Pending'), ('shipped', 'Shipped')], max_length=50)),
                ('products', models.ManyToManyField(to='djcommerce.ProductInCart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
