language: python
sudo: true
cache: pip
python:
  - 3.5
env:
  global:
    - MONGODB=4.1.1
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py27-mock-pymongo-pyexecjs
    - TOX_ENV=pypy-mock-pymongo-pyexecjs
    - TOX_ENV=py34-pymongo-pyexecjs
    - TOX_ENV=py35-pymongo-pyexecjs
    - TOX_ENV=py36-pymongo-pyexecjs
    - TOX_ENV=py37
    - TOX_ENV=py37-pymongo
    - TOX_ENV=py37-pyexecjs
    - TOX_ENV=py37-pymongo-pyexecjs
    - TOX_ENV=pep8
    - TOX_ENV=pylint
matrix:
    # Run all under 3.5 and pypy under pypy, temporary, to be rolled back once trusty fixes it
    include:
        - env: TOX_ENV=pypy-mock-pymongo-pyexecjs
          python: pypy-5.4.1
        - env: TOX_ENV=py36-pymongo-pyexecjs
          python: 3.6
        - env: TOX_ENV=py37
          python: 3.7
          dist: xenial
        - env: TOX_ENV=py37-pymongo
          python: 3.7
          dist: xenial
        - env: TOX_ENV=py37-pyexecjs
          python: 3.7
          dist: xenial
        - env: TOX_ENV=py37-pymongo-pyexecjs
          python: 3.7
          dist: xenial
    exclude:
        - python: 3.5
          env: TOX_ENV=pypy-mock-pymongo-pyexecjs
        - python: 3.5
          env: TOX_ENV=py36-pymongo-pyexecjs
        - python: 3.5
          env: TOX_ENV=py37
        - python: 3.5
          env: TOX_ENV=py37-pymongo
        - python: 3.5
          env: TOX_ENV=py37-pyexecjs
        - python: 3.5
          env: TOX_ENV=py37-pymongo-pyexecjs
script:
  - tox -e $TOX_ENV
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "sudo apt-get update"
before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
after_script:
  - pkill mongod
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - pip install tox
deploy:
  provider: pypi
  user: vmalloc
  distributions: "bdist_wheel sdist"
  password:
    secure: sNOkUNFfWKGsRy4BI+1jyqycZGSMiXTLtpCrX1mTuvjddbndULrHL3ecIPsCno49/nPR4Gww+e9U3HXc8LKJ9qR4mJ8bVCNiHO5GlGVnpV+wdGh9LVnsU1LWwuD8uWlLyTSOKP+ZmerCw7tGACYiv0e9zp8SqZXCH6VS+sAGFxU=
  on:
    tags: true
    all_branches: true
    repo: mongomock/mongomock
