[tool.poetry]
name = "py_tps"
version = "0.1.0"
description = ""
authors = ["ryanfeather"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.14"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
