---
aiohttp_settings:
  client_max_size: 20971520
databases:
- db:
    storage: postgresql
    transaction_strategy: dbresolve_readcommitted
    dsn: postgresql://postgres:secret@localhost:5432/guillotina
    read_only: false
    pool_size: 100
store_json: true
applications:
- guillotina_cms
- guillotina.contrib.cache
# - guillotina_elasticsearch
# - guillotina_linkintegrity
address: 8081
static:
  favicon.png: static/favicon.png
# pastanaga: pastanaga-angular/dist
# ng: plone-angular-demo/dist
# plone: plone-react
root_user:
  password: root
auth_extractors:
- guillotina.auth.extractors.CookiePolicy
- guillotina.auth.extractors.BearerAuthPolicy
- guillotina.auth.extractors.BasicAuthPolicy
- guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
- guillotina.auth.validators.SaltedHashPasswordValidator
- guillotina.auth.validators.JWTValidator
redis:
  host: localhost
  port: 6379
jwt:
  secret: secret
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
cors:
  allow_origin:
  - "*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - OPTIONS
  - PUT
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
