mock_player_data = {"id": 60, "photo": "102046.jpg", "web_name": "Tankovic", "team_code": 1987, "status": "a",
                    "code": 102046, "first_name": "Muamer", "second_name": "Tankovic", "squad_number": 22, "news": "",
                    "now_cost": 92, "news_added": None, "chance_of_playing_this_round": None,
                    "chance_of_playing_next_round": None, "value_form": "0.0", "value_season": "8.8",
                    "cost_change_start": 7,
                    "cost_change_event": 1, "cost_change_start_fall": -7, "cost_change_event_fall": -1,
                    "in_dreamteam": True,
                    "dreamteam_count": 2, "selected_by_percent": "44.4", "form": "0.0", "transfers_out": 1764,
                    "transfers_in": 10413, "transfers_out_event": 100, "transfers_in_event": 177, "loans_in": 0,
                    "loans_out": 0, "loaned_in": 0, "loaned_out": 0, "total_points": 81, "event_points": 0,
                    "points_per_game": "6.8", "ep_this": "0.0", "ep_next": "0.0", "special": False, "minutes": 1017,
                    "goals_scored": 6, "assists": 4, "clean_sheets": 4, "goals_conceded": 13, "penalties_saved": 0,
                    "penalties_missed": 0, "yellow_cards": 2, "red_cards": 0, "saves": 0, "own_goals": 0, "crosses": 3,
                    "key_passes": 21, "big_chances_created": 6, "clearances_blocks_interceptions": 13, "recoveries": 51,
                    "element_type": 3, "team": 3}

mock_league_data = {"new_entries": {"has_next": False, "number": 1, "results": []},
                    "league": {"id": 47, "leagueban_set": [], "name": "Overall", "short_name": "overall",
                               "created": "2019-03-11T13:29:44Z", "closed": False, "forum_disabled": False,
                               "make_code_public": False, "rank": None, "size": None, "league_type": "s",
                               "_scoring": "c",
                               "reprocess_standings": False, "admin_entry": None, "start_event": 1},
                    "standings": {"has_next": True, "number": 1, "results": [
                        {"id": 25431, "entry_name": "Globens Guldgossar", "event_total": 120,
                         "player_name": "Mandus Petersson", "movement": "up", "own_entry": False, "rank": 1,
                         "last_rank": 21,
                         "rank_sort": 1, "total": 871, "entry": 6677, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 1404, "entry_name": "Mainstation.se", "event_total": 109,
                         "player_name": "Joakim Arhammar",
                         "movement": "up", "own_entry": False, "rank": 2, "last_rank": 12, "rank_sort": 2, "total": 868,
                         "entry": 440, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 68040, "entry_name": "Bäst", "event_total": 125, "player_name": "Sofia Asp",
                         "movement": "up",
                         "own_entry": False, "rank": 3, "last_rank": 57, "rank_sort": 3, "total": 858, "entry": 16762,
                         "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 15449, "entry_name": "Utanost", "event_total": 106, "player_name": "Måns Karlsson",
                         "movement": "up", "own_entry": False, "rank": 4, "last_rank": 21, "rank_sort": 4, "total": 857,
                         "entry": 4215, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 26759, "entry_name": "AP Boys", "event_total": 90, "player_name": "Simon Eriksson",
                         "movement": "up", "own_entry": False, "rank": 5, "last_rank": 9, "rank_sort": 5, "total": 852,
                         "entry": 7010, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 40467, "entry_name": "madacorp", "event_total": 84, "player_name": "Oscar Jalgén",
                         "movement": "down", "own_entry": False, "rank": 6, "last_rank": 5, "rank_sort": 6,
                         "total": 846,
                         "entry": 10606, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 49271, "entry_name": "Dalmål FC", "event_total": 76, "player_name": "Magnus Hökback",
                         "movement": "down", "own_entry": False, "rank": 7, "last_rank": 1, "rank_sort": 7,
                         "total": 846,
                         "entry": 12331, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 39017, "entry_name": "Bamboo boys", "event_total": 81, "player_name": "André Jakobsson",
                         "movement": "same", "own_entry": False, "rank": 8, "last_rank": 8, "rank_sort": 8,
                         "total": 844,
                         "entry": 10221, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 20710, "entry_name": "Los gringos", "event_total": 114, "player_name": "Tor Flugstad",
                         "movement": "up", "own_entry": False, "rank": 9, "last_rank": 71, "rank_sort": 9, "total": 843,
                         "entry": 5499, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 31102, "entry_name": "Nacka Nerazzurri", "event_total": 123, "player_name": "Andreas B",
                         "movement": "up", "own_entry": False, "rank": 10, "last_rank": 120, "rank_sort": 10,
                         "total": 843,
                         "entry": 8140, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 101904, "entry_name": "Västra Mark", "event_total": 136, "player_name": "Samuel Vendel",
                         "movement": "up", "own_entry": False, "rank": 11, "last_rank": 198, "rank_sort": 11,
                         "total": 843,
                         "entry": 24194, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 43926, "entry_name": "Jason Björn", "event_total": 91, "player_name": "Daniel Sebestyen",
                         "movement": "up", "own_entry": False, "rank": 12, "last_rank": 25, "rank_sort": 12,
                         "total": 841,
                         "entry": 11088, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 73725, "entry_name": "SambaOffensiv", "event_total": 76,
                         "player_name": "Rasmus Henriksson",
                         "movement": "down", "own_entry": False, "rank": 13, "last_rank": 7, "rank_sort": 13,
                         "total": 840,
                         "entry": 18028, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 30778, "entry_name": "KMK", "event_total": 83, "player_name": "KARL-MAGNUS KARLSSON",
                         "movement": "up", "own_entry": False, "rank": 14, "last_rank": 15, "rank_sort": 14,
                         "total": 840,
                         "entry": 8050, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 63, "entry_name": "Neeps vs Swedes", "event_total": 82,
                         "player_name": "Iain Re1d ???????",
                         "movement": "up", "own_entry": False, "rank": 15, "last_rank": 16, "rank_sort": 15,
                         "total": 838,
                         "entry": 23, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 45498, "entry_name": "---Skamgränsen---", "event_total": 132,
                         "player_name": "Tobias Karlsson", "movement": "up", "own_entry": False, "rank": 16,
                         "last_rank": 250, "rank_sort": 16, "total": 838, "entry": 11421, "league": 47,
                         "start_event": 1,
                         "stop_event": 30},
                        {"id": 4669, "entry_name": "Gult kort", "event_total": 63, "player_name": "Mattias Larsson",
                         "movement": "down", "own_entry": False, "rank": 17, "last_rank": 2, "rank_sort": 17,
                         "total": 834,
                         "entry": 1370, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 4664, "entry_name": "#noccoenough", "event_total": 116, "player_name": "Martin Janson",
                         "movement": "up", "own_entry": False, "rank": 18, "last_rank": 138, "rank_sort": 18,
                         "total": 834,
                         "entry": 1369, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 66082, "entry_name": "Riala 2", "event_total": 84, "player_name": "Andrea Kronvall",
                         "movement": "same", "own_entry": False, "rank": 18, "last_rank": 18, "rank_sort": 19,
                         "total": 834,
                         "entry": 16290, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 18415, "entry_name": "Hasses Hunkar", "event_total": 103, "player_name": "Erik McEwen",
                         "movement": "up", "own_entry": False, "rank": 20, "last_rank": 66, "rank_sort": 20,
                         "total": 833,
                         "entry": 4962, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 11784, "entry_name": "BK Clecio", "event_total": 65, "player_name": "Johan Kämpe",
                         "movement": "down", "own_entry": False, "rank": 21, "last_rank": 4, "rank_sort": 21,
                         "total": 833,
                         "entry": 3298, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 2607, "entry_name": "Another One Irandust", "event_total": 68,
                         "player_name": "Philip Lindblad", "movement": "down", "own_entry": False, "rank": 22,
                         "last_rank": 6, "rank_sort": 22, "total": 833, "entry": 787, "league": 47, "start_event": 1,
                         "stop_event": 30},
                        {"id": 865, "entry_name": "Ådi Merda", "event_total": 64, "player_name": "Robin Zetterman",
                         "movement": "down", "own_entry": False, "rank": 23, "last_rank": 3, "rank_sort": 23,
                         "total": 833,
                         "entry": 274, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 10629, "entry_name": "BK Hisingen", "event_total": 103,
                         "player_name": "Jimi Schlichting",
                         "movement": "up", "own_entry": False, "rank": 24, "last_rank": 68, "rank_sort": 24,
                         "total": 829,
                         "entry": 2991, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 28852, "entry_name": "Gibra FC", "event_total": 85,
                         "player_name": "Markus Gagner-Geeber",
                         "movement": "up", "own_entry": False, "rank": 25, "last_rank": 30, "rank_sort": 25,
                         "total": 828,
                         "entry": 7547, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 7039, "entry_name": "Balle den Rödes", "event_total": 83,
                         "player_name": "Niklas Tysander",
                         "movement": "up", "own_entry": False, "rank": 26, "last_rank": 33, "rank_sort": 26,
                         "total": 826,
                         "entry": 2025, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 34237, "entry_name": "Cookie fc", "event_total": 90, "player_name": "Niclas Johansson",
                         "movement": "up", "own_entry": False, "rank": 26, "last_rank": 45, "rank_sort": 27,
                         "total": 826,
                         "entry": 8962, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 53583, "entry_name": "LA BOIS", "event_total": 68, "player_name": "Mattias Jönsson",
                         "movement": "down", "own_entry": False, "rank": 28, "last_rank": 10, "rank_sort": 28,
                         "total": 826,
                         "entry": 13390, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 48475, "entry_name": "Mackes hjältar", "event_total": 111,
                         "player_name": "Marcus Olsson",
                         "movement": "up", "own_entry": False, "rank": 29, "last_rank": 163, "rank_sort": 29,
                         "total": 825,
                         "entry": 12134, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 52673, "entry_name": "Los 11 impostores", "event_total": 129,
                         "player_name": "Gerardo López Lozada", "movement": "up", "own_entry": False, "rank": 30,
                         "last_rank": 385, "rank_sort": 30, "total": 825, "entry": 13176, "league": 47,
                         "start_event": 1,
                         "stop_event": 30},
                        {"id": 12643, "entry_name": "BPK", "event_total": 116, "player_name": "Joel Rydström",
                         "movement": "up", "own_entry": False, "rank": 31, "last_rank": 175, "rank_sort": 31,
                         "total": 825,
                         "entry": 3514, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 44911, "entry_name": "Monday James", "event_total": 79, "player_name": "Theo Östlund",
                         "movement": "down", "own_entry": False, "rank": 32, "last_rank": 28, "rank_sort": 32,
                         "total": 824,
                         "entry": 11300, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 5348, "entry_name": "Fc Gröna Bröder", "event_total": 76,
                         "player_name": "Jacob Andersson",
                         "movement": "down", "own_entry": False, "rank": 33, "last_rank": 26, "rank_sort": 33,
                         "total": 824,
                         "entry": 1573, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 32846, "entry_name": "FC Lyseblå", "event_total": 61, "player_name": "Wilhelm Börjesson",
                         "movement": "down", "own_entry": False, "rank": 34, "last_rank": 11, "rank_sort": 34,
                         "total": 823,
                         "entry": 8601, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 86922, "entry_name": "VirreIF", "event_total": 70, "player_name": "Viktor Johansson",
                         "movement": "down", "own_entry": False, "rank": 35, "last_rank": 19, "rank_sort": 35,
                         "total": 822,
                         "entry": 20906, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 14995, "entry_name": "Fängsla Kindberg", "event_total": 113,
                         "player_name": "Axel Edvardsson",
                         "movement": "up", "own_entry": False, "rank": 36, "last_rank": 169, "rank_sort": 36,
                         "total": 822,
                         "entry": 4097, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 77879, "entry_name": "Noll boll kontroll", "event_total": 128,
                         "player_name": "Jonas Hållander", "movement": "up", "own_entry": False, "rank": 37,
                         "last_rank": 430, "rank_sort": 37, "total": 821, "entry": 18959, "league": 47,
                         "start_event": 1,
                         "stop_event": 30},
                        {"id": 2935, "entry_name": "Big Mäk & co", "event_total": 78, "player_name": "Henrik Mäkitalo",
                         "movement": "down", "own_entry": False, "rank": 38, "last_rank": 30, "rank_sort": 38,
                         "total": 821,
                         "entry": 880, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 58902, "entry_name": "Hunden Leif", "event_total": 63,
                         "player_name": "Sebastian Gille-Johnson", "movement": "down", "own_entry": False, "rank": 38,
                         "last_rank": 13, "rank_sort": 39, "total": 821, "entry": 14575, "league": 47, "start_event": 1,
                         "stop_event": 30},
                        {"id": 6818, "entry_name": "TeamTräben", "event_total": 86, "player_name": "Jakob Hallén",
                         "movement": "up", "own_entry": False, "rank": 40, "last_rank": 51, "rank_sort": 40,
                         "total": 821,
                         "entry": 1965, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 29991, "entry_name": "Garys hjältar", "event_total": 78, "player_name": "Magnus Aggebo",
                         "movement": "down", "own_entry": False, "rank": 40, "last_rank": 30, "rank_sort": 41,
                         "total": 821,
                         "entry": 7844, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 1051, "entry_name": "Tyrannosaurus Rieks", "event_total": 88,
                         "player_name": "Tobias Lundin",
                         "movement": "same", "own_entry": False, "rank": 42, "last_rank": 42, "rank_sort": 42,
                         "total": 821,
                         "entry": 331, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 6631, "entry_name": "Landskrona IP", "event_total": 63, "player_name": "Philip Wetzler",
                         "movement": "down", "own_entry": False, "rank": 43, "last_rank": 14, "rank_sort": 43,
                         "total": 820,
                         "entry": 1918, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 85711, "entry_name": "Jag sa till dig", "event_total": 125,
                         "player_name": "Christoph Issa",
                         "movement": "up", "own_entry": False, "rank": 43, "last_rank": 391, "rank_sort": 44,
                         "total": 820,
                         "entry": 20645, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 257, "entry_name": "Good Vibes", "event_total": 68, "player_name": "Albin Johansson",
                         "movement": "down", "own_entry": False, "rank": 45, "last_rank": 24, "rank_sort": 45,
                         "total": 818,
                         "entry": 87, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 2562, "entry_name": "Kullmans Pojkar", "event_total": 130,
                         "player_name": "Oskar Kullman",
                         "movement": "up", "own_entry": False, "rank": 45, "last_rank": 549, "rank_sort": 46,
                         "total": 818,
                         "entry": 774, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 6852, "entry_name": "FC Henri Duflot", "event_total": 70,
                         "player_name": "Alexander Stempel",
                         "movement": "down", "own_entry": False, "rank": 47, "last_rank": 19, "rank_sort": 47,
                         "total": 818,
                         "entry": 1974, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 5873, "entry_name": "Lovely Yellow Cards", "event_total": 109,
                         "player_name": "Jonas Höglund",
                         "movement": "up", "own_entry": False, "rank": 48, "last_rank": 185, "rank_sort": 48,
                         "total": 817,
                         "entry": 1723, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 6969, "entry_name": "Knakelibraksuksess", "event_total": 93,
                         "player_name": "Jan Inge Nordby",
                         "movement": "up", "own_entry": False, "rank": 49, "last_rank": 93, "rank_sort": 49,
                         "total": 817,
                         "entry": 2006, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 29448, "entry_name": "Såsen", "event_total": 78, "player_name": "Christoffer Hult",
                         "movement": "down", "own_entry": False, "rank": 50, "last_rank": 34, "rank_sort": 50,
                         "total": 816,
                         "entry": 7702, "league": 47, "start_event": 1, "stop_event": 30},
                        {"id": 18212, "entry_name": "Utrechters", "event_total": 79, "player_name": "Göktug Erce Gürel",
                         "movement": "down", "own_entry": True, "rank": 153, "last_rank": 150, "rank_sort": 153,
                         "total": 791, "entry": 4911, "league": 47, "start_event": 1, "stop_event": 30}]},
                    "update_status": 0}

mock_league_entry = {"id": 25431, "entry_name": "Globens Guldgossar", "event_total": 120,
                     "player_name": "Mandus Petersson", "movement": "up", "own_entry": False, "rank": 1,
                     "last_rank": 21,
                     "rank_sort": 1, "total": 871, "entry": 6677, "league": 47, "start_event": 1, "stop_event": 30}

mock_team_data = {"active_chip": "pdbus",
                  "automatic_subs": [{"id": 599443, "element_in": 9, "element_out": 201, "entry": 6677, "event": 13}],
                  "entry_history": {"id": 595786, "movement": "new", "points": 120, "total_points": 871, "rank": 102,
                                    "rank_sort": 102, "overall_rank": 1, "targets": None, "event_transfers": 2,
                                    "event_transfers_cost": 0, "value": 1022, "points_on_bench": 3, "bank": 28,
                                    "entry": 6677, "event": 13},
                  "event": {"id": 13, "name": "Round 13", "deadline_time": "2019-06-25T16:00:00Z",
                            "average_entry_score": 59,
                            "finished": True, "data_checked": True, "highest_scoring_entry": 5715,
                            "deadline_time_epoch": 1561478400, "deadline_time_game_offset": 7200,
                            "deadline_time_formatted": "25 jun 18:00", "highest_score": 144, "is_previous": False,
                            "is_current": True, "is_next": False},
                  "picks": [
                      {"element": 9, "position": 1, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 379, "position": 2, "is_captain": False, "is_vice_captain": False, "multiplier": 2},
                      {"element": 400, "position": 3, "is_captain": False, "is_vice_captain": False, "multiplier": 2},
                      {"element": 211, "position": 4, "is_captain": False, "is_vice_captain": False, "multiplier": 2},
                      {"element": 291, "position": 5, "is_captain": False, "is_vice_captain": False, "multiplier": 2},
                      {"element": 284, "position": 6, "is_captain": False, "is_vice_captain": False, "multiplier": 2},
                      {"element": 43, "position": 7, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 370, "position": 8, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 203, "position": 9, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 380, "position": 10, "is_captain": False, "is_vice_captain": True, "multiplier": 1},
                      {"element": 283, "position": 11, "is_captain": True, "is_vice_captain": False, "multiplier": 1},
                      {"element": 201, "position": 12, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 60, "position": 13, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 148, "position": 14, "is_captain": False, "is_vice_captain": False, "multiplier": 1},
                      {"element": 261, "position": 15, "is_captain": False, "is_vice_captain": False,
                       "multiplier": 1}]}

mock_pick_data = {"element": 379, "position": 2, "is_captain": False, "is_vice_captain": False, "multiplier": 2}

mock_teams_data = [
    {"active_chip": "Park the Bus", "id": 6677, "picks": [
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 9, "position": 1, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 379, "position": 2, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 400, "position": 3, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 211, "position": 4, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 291, "position": 5, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 284, "position": 6, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 43, "position": 7, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 370, "position": 8, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 203, "position": 9, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 380, "position": 10, "vice_captain": True},
        {"benched": False, "captain": True, "multiplier": 1, "player_id": 283, "position": 11, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 201, "position": 12, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 60, "position": 13, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 148, "position": 14, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 261, "position": 15, "vice_captain": False}]},
    {"active_chip": "Park the Bus", "id": 440, "picks": [
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 386, "position": 1, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 387, "position": 2, "vice_captain": True},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 291, "position": 3, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 211, "position": 4, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 392, "position": 5, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 272, "position": 6, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 24, "position": 7, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 359, "position": 8, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 43, "position": 9, "vice_captain": False},
        {"benched": False, "captain": True, "multiplier": 1, "player_id": 283, "position": 10, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 183, "position": 11, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 308, "position": 12, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 113, "position": 13, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 117, "position": 14, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 148, "position": 15, "vice_captain": False}]},
    {"active_chip": "Park the Bus", "id": 16762, "picks": [
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 9, "position": 1, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 272, "position": 2, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 291, "position": 3, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 400, "position": 4, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 379, "position": 5, "vice_captain": False},
        {"benched": False, "captain": True, "multiplier": 2, "player_id": 211, "position": 6, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 24, "position": 7, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 203, "position": 8, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 112, "position": 9, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 380, "position": 10, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 283, "position": 11, "vice_captain": True},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 25, "position": 12, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 60, "position": 13, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 200, "position": 14, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 148, "position": 15, "vice_captain": False}]},
    {"active_chip": "Park the Bus", "id": 4215, "picks": [
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 25, "position": 1, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 211, "position": 2, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 392, "position": 3, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 291, "position": 4, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 272, "position": 5, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 387, "position": 6, "vice_captain": False},
        {"benched": False, "captain": True, "multiplier": 1, "player_id": 203, "position": 7, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 31, "position": 8, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 380, "position": 9, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 283, "position": 10, "vice_captain": True},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 218, "position": 11, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 9, "position": 12, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 60, "position": 13, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 117, "position": 14, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 148, "position": 15, "vice_captain": False}]},
    {"active_chip": "Attack! Attack!", "id": 7010, "picks": [
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 288, "position": 1, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 387, "position": 2, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 211, "position": 3, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 202, "position": 4, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 148, "position": 5, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 24, "position": 6, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 60, "position": 7, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 1, "player_id": 394, "position": 8, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 380, "position": 9, "vice_captain": True},
        {"benched": False, "captain": True, "multiplier": 2, "player_id": 283, "position": 10, "vice_captain": False},
        {"benched": False, "captain": False, "multiplier": 2, "player_id": 183, "position": 11, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 255, "position": 12, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 215, "position": 13, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 59, "position": 14, "vice_captain": False},
        {"benched": True, "captain": False, "multiplier": 1, "player_id": 145, "position": 15, "vice_captain": False}]}
]
