
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-02T13:36:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "87f17dabd706f03db8d5ab339de4e5bf9c8ebd8b",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
