# Generated by Django 2.2 on 2019-04-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0042_auto_20190420_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepoperation',
            options={'ordering': ['-started_time', '-completed_time', '-pk'], 'verbose_name': 'operation'},
        ),
    ]
