TASK_STATUS_FINISHED = 'finished'
WHATSAPP_CONTENT = 'Contenido:'
WHATSAPP_DIVIDER = '-----------------------------'
WHATSAPP_FROM = 'De:'
WHATSAPP_INLINE_DIVIDER = '\n'
WHATSAPP_TIMESTAMP = 'Marca de hora:'
