
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-02T13:52:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ade52a2d1afe22bdff0ac28b65e5b5cfdd03dd44",
 "version": "0+untagged.448.gade52a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
